/**
 * IActivityService
 *
 * Application-facing contract for Activity operations.
 *
 * Responsibilities:
 * - Record workspace events (called internally by other services)
 * - Provide Activity history for Timelines and audit views
 *
 * Rules:
 * - No repository types, storage types, or infrastructure imports
 * - Activities are append-only — no update or archive operations
 * - Activities are generated by services, never by the UI directly
 * - The full Activity stream is the foundation for Timelines and analytics
 *
 * @see docs/04_assignment_lifecycle.md (Automatic System Actions)
 * @see docs/03.5_system_architecture.md (Event-Driven Thinking)
 * @see docs/09_technical_architecture.md (Application Layer)
 */

import type {
  Activity,
  ActivityType,
  CreateActivityInput,
  AnyDomainError,
  EntityId,
} from '@domain';

export interface IActivityService {
  // ─── Write operations ───────────────────────────────────────────────────────

  /**
   * Records a new Activity in the Workspace event stream.
   *
   * Called internally by other services after every meaningful transition.
   * The UI should never call this method directly — Activities must be
   * generated as a consequence of a business operation, not in isolation.
   *
   * @see docs/04_assignment_lifecycle.md (Rule 5 — every transition generates an Activity)
   */
  recordActivity(
    input: CreateActivityInput,
  ): Promise<Activity | AnyDomainError>;

  // ─── Read operations ────────────────────────────────────────────────────────

  /**
   * Returns all Activities in the given Workspace,
   * ordered by timestamp ascending (oldest first).
   *
   * This is the primary input for the Workspace Timeline.
   */
  getActivitiesByWorkspace(
    workspaceId: EntityId,
  ): Promise<Activity[] | AnyDomainError>;

  /**
   * Returns all Activities related to the given Assignment,
   * ordered by timestamp ascending.
   *
   * Used to reconstruct the Assignment Timeline.
   */
  getActivitiesByAssignment(
    assignmentId: EntityId,
  ): Promise<Activity[] | AnyDomainError>;

  /**
   * Returns all Activities involving the given Contributor
   * within the given Workspace, ordered by timestamp ascending.
   *
   * Used to reconstruct the Contributor Timeline and Ledger.
   */
  getActivitiesByContributor(
    workspaceId: EntityId,
    contributorId: EntityId,
  ): Promise<Activity[] | AnyDomainError>;

  /**
   * Returns all Activities of the given type in the given Workspace,
   * ordered by timestamp ascending.
   *
   * Used for targeted audit queries and derived analytics.
   */
  getActivitiesByType(
    workspaceId: EntityId,
    type: ActivityType,
  ): Promise<Activity[] | AnyDomainError>;
}
